# PROCEDURE addNewMember(NAME : STRING, MEMBERID : STRING, CATEGORY : STRING)
#
# END PROCEDURE

# PROCEDURE printMembershipCard(NAME : STRING, MEMBERID : STRING, CATEGORY : STRING)
#
# END PROCEDURE

# PROCEDURE calculateTotalMembers(MEMBERSJ : ARRAY[1:20,1:2] OF STRING, MEMBERSS : ARRAY[1:20,1:2] OF STRING, MEMBERSSTD : ARRAY[1:20,1:2] OF STRING, NOJUNIORS : INTEGER, NOSENIORS : INTEGER, NOSTANDARDS : INTEGER)
#
# END PROCEDURE

# PROCEDURE deleteMember(MEMBERID : STRING, MEMBERSJ : ARRAY[1:20,1:2] OF STRING, MEMBERS : ARRAY[1:20,1:2] OF STRING, MEMBERSSTD : ARRAY[1:20,1:2] OF STRING)
#
# END PROCEDURE